### ISSUE TITLE
lovr 0.14: presence of a conf.lua on Windows makes boot fail

### ISSUE THREAD

**Issue by nevyn** [mcclure/lodr#1]
If a conf.lua is present in the game folder, lodr throws an error on lovr master/0.14. 

The error is `boot.lua:141: conf.lua:20: module 'tempConfDir.conf' not found`

![image](https://user-images.githubusercontent.com/34791/71786281-fca91600-3009-11ea-9e63-36b2bad86b68.png)

**Comment by mcclure** [comment]
Reproduces on mac.

**Comment by mcclure** [comment]
In my testing this is fixed in lovr master as of https://github.com/bjornbytes/lovr/commit/f207c4d9a4cd63fa7d54033dc9e243c54e281d28 . Please upgrade your lovr and let me know if you have any further problems
